path:
  tracking_uri: "sqlite:///mlflow.db"
  artifacts_path: "../output/"

experiment:
  base_train: "green-taxi-experiment"
  hyper_params_rf_train: "green-taxi-rf-hyperopt"
  best_models_run: "random-forest-best-models"

logger:
  log_path: "log/dump.log"
  log_level: "debug"
